const REQUEST_DETAILREPORTS = 'detailReports/REQUEST_DETAILREPORTS';
const REQUEST_LATEST_DETAILREPORTS = 'detailReports/REQUEST_LATEST_DETAILREPORTS';
const RECEIVE_DETAILREPORTS = 'detailReports/RECEIVE_DETAILREPORTS';
const RECEIVE_LATEST_DETAILREPORTS = 'detailReports/RECEIVE_LATEST_DETAILREPORTS';
export {
  REQUEST_DETAILREPORTS,
  REQUEST_LATEST_DETAILREPORTS,
  RECEIVE_DETAILREPORTS,
  RECEIVE_LATEST_DETAILREPORTS,
};
